server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: 47376543931

logging:
  config: classpath:logback.xml

spring:
  http:
    converters:
      preferred-json-mapper: fastjson
  devtools:
      restart:
        enabled: true
  profiles:
      active: dev




