server:
  port: 8080

logging:
  config: classpath:logback.xml

spring:
  http:
    converters:
      preferred-json-mapper: fastjson
  devtools:
      restart:
        enabled: true

  # redis 集群配置
  redis:
       cluster:
          nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005

  # 邮箱配置
  mail:
      host: smtp.exmail.qq.com
      username: yinliwen@bjscfl.com
      password: 1234qweR
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
  profiles:
      active: dev

  # 数据源配置
  datasource:
    name: scfl
    url: jdbc:mysql://127.0.0.1:3306/procurement_system?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  resources:
    static-locations: file:${kuaige.generate.imgPath}
  mvc:
    static-path-pattern: ${kuaige.generate.staticBrowsePath}**

# 快鸽自定义配置信息
kuaige:
  generate:
      excelSavePath: /data/template/excel
      imgPath: /data/template/img/
      staticBrowsePath: /static/img/
  mail:
    report:
      subject: 报表信息
      content: 由快鸽发送的报表信息！





