server:
  port: 8443
  ssl:
    key-store: classpath:certificate/keystore.jks
    key-store-password: 47376543931

logging:
  config: classpath:log/logback-spring.xml

spring:
  http:
    converters:
      preferred-json-mapper: fastjson
  devtools:
      restart:
        enabled: true
  # 邮箱配置
  mail:
      host: smtp.exmail.qq.com
      username: yinliwen@bjscfl.com
      password: 1234qweR
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
              port: 465
  profiles:
      active: @profileActive@






