server:
  port: 8443
  ssl:
    key-store: classpath:certificate/keystore.jks
    key-store-password: 47376543931

logging:
  config: classpath:log/logback-spring.xml

spring:
  http:
    converters:
      preferred-json-mapper: fastjson
  devtools:
      restart:
        enabled: true
  profiles:
      active: @profileActive@






