server:
  port: 8443
  ssl:
    key-store: classpath:certificate/keystore.jks
    key-store-password: 50167515853

spring:
  http:
    converters:
      preferred-json-mapper: fastjson
  devtools:
      restart:
        enabled: true
  jackson:
    #参数意义：
    #JsonInclude.Include.ALWAYS       默认
    #JsonInclude.Include.NON_DEFAULT   属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY     属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL      属性为NULL  不序列化
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # 邮箱配置
  mail:
      host: smtp.qq.com
      username: 3393024626@qq.com
      password: gfyboxieuibgcifh
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
              port: 465
  profiles:
      active: @profileActive@






