server:
  port: 8089

logging:
  config: classpath:logback/logback-spring.xml

spring:
  http:
    converters:
      preferred-json-mapper: fastjson
  devtools:
      restart:
        enabled: true
  profiles:
      active: @profileActive@






